baseURL = "https://sysctl.ru/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "SysCtl"
theme = "anatole"
summarylength = 10
enableEmoji = false
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Alexey V. Grebenshchikov"
author = "Alexey V. Grebenshchikov"
description = "My personal blog"
profilePicture = "images/avg.jpeg"
keywords = ""
#favicon = "favicons/"
customCss = ["css/fontawesome.css"]
mainSections = ["posts"]
#images = []
doNotLoadAnimations = true
disableThemeSwitcher = true
fullPostContent = true

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/aleksiog/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/livestalker"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mi.aleksio@gmail.com"

[Languages]
  [Languages.ru]
  weight = 2
  contentDir = "content/rus"
  LanguageName = "RU"

  [Languages.en]
  weight = 1
  contentDir = "content/eng"
  LanguageName = "EN"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/cv/"

#  [[menu.main]]
#  name = "Contact"
#  weight = 400
#  identifier = "contact"
#  url = "/contact/"
  
  # RU menu
  [[Languages.ru.menu.main]]
  name = "Главная"
  identifier = "home"
  weight = 100
  url = "/ru/"

  [[Languages.ru.menu.main]]
  name = "Посты"
  weight = 200
  identifier = "posts"
  url = "/ru/posts/"

  [[Languages.ru.menu.main]]
  name = "CV"
  weight = 300
  identifier = "cv"
  url = "/ru/cv/"

#  [[Languages.ru.menu.main]]
#  name = "Контактная информация"
#  weight = 400
#  identifier = "contact"
#  url = "/ru/contact/"

[markup.goldmark.renderer]
unsafe = true
